name: Build APK

on:
  workflow_dispatch:
    inputs:
      zip_path:
        required: true
      job_id:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ===== DOWNLOAD ZIP =====
      - name: Download ZIP
        run: |
          mkdir project
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -L https://api.github.com/repos/${{ github.repository }}/contents/${{ github.event.inputs.zip_path }} \
          | jq -r .content | base64 -d > project/app.zip

      - name: Unzip
        run: unzip project/app.zip -d project

      # ===== SETUP JAVA (WAJIB BUAT ANDROID) =====
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      # ===== SETUP ANDROID SDK =====
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # ===== SETUP FLUTTER =====
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"
          cache: true

      # ===== ACCEPT LICENSE =====
      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      # ===== BUILD APK =====
      - name: Build APK
        run: |
          cd project
          flutter pub get
          flutter build apk --release

      # ===== UPLOAD APK =====
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.event.inputs.job_id }}
          path: project/build/app/outputs/flutter-apk/app-release.apk
