name: Build APK

on:
  workflow_dispatch:
    inputs:
      zip_path:
        required: true
      job_id:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download ZIP
        run: |
          mkdir project
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -L https://api.github.com/repos/${{ github.repository }}/contents/${{ github.event.inputs.zip_path }} \
          | jq -r .content | base64 -d > project/app.zip

      - name: Unzip
        run: unzip project/app.zip -d project

      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Build APK
        run: |
          cd project
          flutter pub get
          flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.event.inputs.job_id }}
          path: project/build/app/outputs/flutter-apk/app-release.apk
